### ISSUE TITLE
typeop constraints blocking each other

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#124]
``` 
typecheck_hs_from_string("function sloop(x::Integer, n::Integer)
                   for i in 1:2:n
                       x = x+x+n
                   end
                   x
               end
       ")
```
gives
```
 (Fun([([NoFun(Num(τ_42)) @ 1,NoFun(Num(Int[--])) @ 0.5 + ∞⋅η_13] -> NoFun(Num(τ_42))) @ Just [Integer,Integer]])
```
with the (non-resolvable!) constraints
```
constr_27 : [final,worst,global,exact,special] IsEqual (η_15⋅η_12 + η_14⋅η_12,1),
constr_6 : [final,worst,global,exact,special] IsTypeOpResult (Binary + (Num(τ_41) @ η_12,Num(Int[--]) @ η_13) Num(τ_42)),
constr_7 : [final,worst,global,exact,special] IsTypeOpResult (Binary + (Num(τ_42) @ η_14,Num(τ_42) @ η_15) Num(τ_41)),
constr_19 : [final,worst,global,exact,special] IsLessEqual (τ_42,Int[--])
```
i think the issue is that in before making a type non-const to resolve typeop constraints we check whether it appears in any other constraints. i don't think we have to do that as long as we don't actually unify the tvars with the non-const thing but only resolve the op constraint as if they were non-const?

**Comment by MxmUrw** [comment]
Hm, but is that still correct then? (I think the proper solution would be something like finding connected components in the reference graph, and then checking if it is allowed to make a full component NonConst... which we obviously will not do).

Yeah, I think your proposition is correct, because the only bad thing that might happen is that later we actually do find out that something was const, but here in the constraint we assumed that it is nonconst. Thus we have a worse result than necessary (if we were to this non-constification in a better order).

Another thing to watch out for now is the question of what do you if you do not know that (Int vs Real) BaseNumType of the input. Because it seems we still would need to have some type variable for the nonconst version (which we now create without unification), but how do you link that one to the original - without unification?

**Comment by MxmUrw** [comment]
Or is that last question really relevant (because of second paragraph)? Anyways, I think if it is possible to implement this without blocking it should be fine.

**Comment by ooovi** [comment]
well the actual type of the number affects the return type, so for that we cannot make any assumptions. so yes, we will have to make unifications after all. is that even a problem? that is to say, why can typeOp constraints block each other at all?

**Comment by MxmUrw** [comment]
Well the blocking comes from the fact that we do unification when non-constifying. When we have a constraint `a + b = c` and one `c + d = e`, and now we decide to non-constify `c` in order to solve the second constraint, this changes the `c` in the first constraint, which later might say that `c` is actually const.

**Comment by ooovi** [comment]
well this should only happen at a stage where we arbitrarily make things non-const to get less constraints so i think your special case solution is fine.

another thing that could bring relief in some cases is to only make a typeOp constraint blocking if its return type occurs in the current constraint. not this example, but another one i'm having trouble with

**Comment by MxmUrw** [comment]
What kind of situation are we talking about now? How is it related to the current one? And would we do that additionally to my proposed solution, or instead of?
