### ISSUE TITLE
find the reason we have to do two rounds of constraint resolving

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#129]
the hotfix works but it would be nice to know why running resolution once does not suffice

**Comment by MxmUrw** [comment]
This is because we have the "hat"-types, `:∧:`. On NoFuns, they unify their entries. And unification of types containing sensitivities may result in new sensitivity equality constraints.

What we can do is write a function which does as many iterations as necessary until constraints do not change anymore.
