### ISSUE TITLE
Implementing julia scoping/capturing by implicit variables

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#20]
Typechecking of the following code would proceed as following.

```julia
let d = ?
let e = ?

function g(f,a)  
    # => (g :: {b @ sb1}(f :: {a,b}(a) -> F, a :: (A :@ (2 * (sa1+sa2))))) -> F
  let a = 2*(1+a)
    # => check (2*a): {(a :@ 2) :: A}
    # => new {(a :@ (2 * (sa1+sa2))), (b @ sb1)}
  in f{a,b}(a)
    # => (f :: {(a1,sa1) :: A, (b1,sb1) :: B}((a2,sa2) :: A) -> F)
end
function f(x) :: {(b,1) :: B}((x,3) :: Int) -> B
  b + 3*x
end
b = e
g(f,d)
  # => IFA(g :: {b @ sb1}(f :: {a,b}(a) -> F, a :: (A :@ (2 * (sa1+sa2))))) -> F
  #    , [({(b,1) :: B}((x,3) :: Int) -> B), D] -> G)
```

**Comment by ooovi** [comment]
there is a problem if we want to check functions without knowing the scope they are applied in. consider this example:

```
function f(x)
   2*y
end
function f()
   x + y
end
function test()
   f()
end
y = 1
x = 1
test()
```

if we want to check `test`, we need to make sure none of its implicit or explicit parameters (hence, `f`), has any unresolved implicit parameters itself. that can be done by recursively resolving all implicit parameters of all parameters upon application of `test()`. but we cannot know whether the call of `test()` is 1- or 2-sensitive in `y`, as we do not yet know which method of `f` will be called, so actually resolving would be super cmplicated.

another drawback: we have to deactivate choices that use variables that are not in the scope without removing them from the choice list. an `f(x,y) = z` choice cannot be taken from the list of choices in case `test` calls an f with two parameters, but it must yield an error if it is chosen because it uses `z` which was never defined.

**Comment by MxmUrw** [comment]
This approach is on hold in favor of #22.
