### ISSUE TITLE
using `==!` instead of `unify` leads to leftover constraints

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#53]
e.g. this function
```
 t = string_to_dmterm("function f(x::Integer) :: Priv()
                     (theta, mu) = (100,x)
                     theta + mu
                     end")
```
when using `==!` in the [checking of the `TLet` term](https://github.com/DiffMu/DiffPrivacyInferenceHs/blob/cfdf2048acc6f287dcca879cd84915d8eda3bf23/src/DiffMu/Typecheck/Typecheck.hs#L391) leads to remaining constraints of
```
constr_8 : [global,worst,global,exact] IsSupremum (τ_30,τ_31) :=: τ_32,
constr_7 : [global,worst,global,exact] IsLessEqual (τ_28,Int[--])
```
while when using unification there are no leftover constraints. see #50,  cfdf204

**Comment by MxmUrw** [comment]
This bug is happening because when rewriting unification, I accidentally made it forget about equations when the two sides could not be unified immediately. (instead of creating an `IsEqual` constraint, [here](https://github.com/DiffMu/DiffPrivacyInferenceHs/blob/cfdf2048acc6f287dcca879cd84915d8eda3bf23/src/DiffMu/Core/Unification.hs#L170-L172)).

This led to the case that the unification of
```
Force[Check]: Got wait in unify on (τ_13∧τ_7) ==! NoFun(Tupl([Num(Int[100.0]),τ_20]))
```
was simply dropped, and the types of the tuple elements weren't forwarded anywhere, thus the unsolved constraint remained.
